CREATE TABLE ghostwriterz_users(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITy,
    fullname TEXT NOT NULL,
    username TEXT NOT NULL UNIQUE,
    nickname TEXT,
    password TEXT,
    date_created TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE lyric_data
ADD COLUMN
artist INTEGER REFERENCES ghostwriterz_users(id)
ON DELETE SET NULL;